name: TheWildEscape
version: 0.1
main: teamdjg.wildescape.main.Main
commands:
    CreateTeam:
        description: creates a team for the Wild Escape Game.
        usage: /<command>
    bordersetup:
        description: setup the worldborder variables.
        usage: /<command> [border minimum(number)] [border maximum(number)] [border distance per night(number)] [border speed per night(number)]
        aliases: [bordersetup, bsetup, bse]
    bordercenter:
        description: place the center of the border on the place where you stand when activating the commmand.
        usage: /<command>
        aliases: [bordercenter, bcenter, bc]